package flightreservationfrontend;


/**
* flightreservationfrontend/FlightReservationFrontEndHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/alvaro/Documents/Workspaces/eclipse/FT_HA_DistFlightR/src/FlightReservationFrontEnd.idl
* Tuesday, November 15, 2016 7:27:40 PM EST
*/

abstract public class FlightReservationFrontEndHelper
{
  private static String  _id = "IDL:flightreservationfrontend/FlightReservationFrontEnd:1.0";

  public static void insert (org.omg.CORBA.Any a, flightreservationfrontend.FlightReservationFrontEnd that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static flightreservationfrontend.FlightReservationFrontEnd extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (flightreservationfrontend.FlightReservationFrontEndHelper.id (), "FlightReservationFrontEnd");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static flightreservationfrontend.FlightReservationFrontEnd read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FlightReservationFrontEndStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, flightreservationfrontend.FlightReservationFrontEnd value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static flightreservationfrontend.FlightReservationFrontEnd narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof flightreservationfrontend.FlightReservationFrontEnd)
      return (flightreservationfrontend.FlightReservationFrontEnd)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      flightreservationfrontend._FlightReservationFrontEndStub stub = new flightreservationfrontend._FlightReservationFrontEndStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static flightreservationfrontend.FlightReservationFrontEnd unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof flightreservationfrontend.FlightReservationFrontEnd)
      return (flightreservationfrontend.FlightReservationFrontEnd)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      flightreservationfrontend._FlightReservationFrontEndStub stub = new flightreservationfrontend._FlightReservationFrontEndStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
