package flightreservationfrontend;

/**
* flightreservationfrontend/FlightReservationFrontEndHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/alvaro/Documents/Workspaces/eclipse/FT_HA_DistFlightR/src/FlightReservationFrontEnd.idl
* Tuesday, November 15, 2016 7:27:40 PM EST
*/

public final class FlightReservationFrontEndHolder implements org.omg.CORBA.portable.Streamable
{
  public flightreservationfrontend.FlightReservationFrontEnd value = null;

  public FlightReservationFrontEndHolder ()
  {
  }

  public FlightReservationFrontEndHolder (flightreservationfrontend.FlightReservationFrontEnd initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = flightreservationfrontend.FlightReservationFrontEndHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    flightreservationfrontend.FlightReservationFrontEndHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return flightreservationfrontend.FlightReservationFrontEndHelper.type ();
  }

}
