package flightreservationfrontend;


/**
* flightreservationfrontend/FlightReservationFrontEnd.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/alvaro/Documents/Workspaces/eclipse/FT_HA_DistFlightR/src/FlightReservationFrontEnd.idl
* Tuesday, November 15, 2016 7:27:40 PM EST
*/

public interface FlightReservationFrontEnd extends FlightReservationFrontEndOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FlightReservationFrontEnd
