package flightreservation;


/**
* flightreservation/FlightReservationSystemPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/alvaro/Documents/Workspaces/eclipse/CorbaFlightReservation/src/FlightReservation.idl
* Wednesday, October 26, 2016 8:08:12 PM EDT
*/

public abstract class FlightReservationSystemPOA extends org.omg.PortableServer.Servant
 implements flightreservation.FlightReservationSystemOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("editFlightRecord", new java.lang.Integer (0));
    _methods.put ("getBookedFlightCount", new java.lang.Integer (1));
    _methods.put ("transferReservation", new java.lang.Integer (2));
    _methods.put ("bookFlight", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // flightreservation/FlightReservationSystem/editFlightRecord
       {
         String adminUser = in.read_string ();
         String flightInfo = in.read_string ();
         short operationType = in.read_short ();
         String $result = null;
         $result = this.editFlightRecord (adminUser, flightInfo, operationType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // flightreservation/FlightReservationSystem/getBookedFlightCount
       {
         short type = in.read_short ();
         String $result = null;
         $result = this.getBookedFlightCount (type);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // flightreservation/FlightReservationSystem/transferReservation
       {
         short passengerId = in.read_short ();
         String currentCity = in.read_string ();
         String destinationCity = in.read_string ();
         String $result = null;
         $result = this.transferReservation (passengerId, currentCity, destinationCity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // flightreservation/FlightReservationSystem/bookFlight
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String address = in.read_string ();
         String phone = in.read_string ();
         String destination = in.read_string ();
         int date = in.read_long ();
         short type = in.read_short ();
         String $result = null;
         $result = this.bookFlight (firstName, lastName, address, phone, destination, date, type);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:flightreservation/FlightReservationSystem:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FlightReservationSystem _this() 
  {
    return FlightReservationSystemHelper.narrow(
    super._this_object());
  }

  public FlightReservationSystem _this(org.omg.CORBA.ORB orb) 
  {
    return FlightReservationSystemHelper.narrow(
    super._this_object(orb));
  }


} // class FlightReservationSystemPOA
