package CorbaServers;


/**
* CorbaServers/ICounterServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaServers.idl
* Tuesday, November 8, 2016 5:52:34 PM EST
*/

abstract public class ICounterServerHelper
{
  private static String  _id = "IDL:CorbaServers/ICounterServer:1.0";

  public static void insert (org.omg.CORBA.Any a, CorbaServers.ICounterServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CorbaServers.ICounterServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CorbaServers.ICounterServerHelper.id (), "ICounterServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CorbaServers.ICounterServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ICounterServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CorbaServers.ICounterServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CorbaServers.ICounterServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CorbaServers.ICounterServer)
      return (CorbaServers.ICounterServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CorbaServers._ICounterServerStub stub = new CorbaServers._ICounterServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CorbaServers.ICounterServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CorbaServers.ICounterServer)
      return (CorbaServers.ICounterServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CorbaServers._ICounterServerStub stub = new CorbaServers._ICounterServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
