package CorbaServers;


/**
* CorbaServers/ICounterServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaServers.idl
* Tuesday, November 8, 2016 5:52:34 PM EST
*/

public interface ICounterServerOperations 
{
  int getNext ();
} // interface ICounterServerOperations
