package CorbaServers;

/**
* CorbaServers/IFlightServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaServers.idl
* Tuesday, November 8, 2016 5:52:34 PM EST
*/

public final class IFlightServerHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaServers.IFlightServer value = null;

  public IFlightServerHolder ()
  {
  }

  public IFlightServerHolder (CorbaServers.IFlightServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaServers.IFlightServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaServers.IFlightServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaServers.IFlightServerHelper.type ();
  }

}
