package CorbaServers;


/**
* CorbaServers/IFlightServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaServers.idl
* Tuesday, November 8, 2016 5:52:34 PM EST
*/

public interface IFlightServerOperations 
{
  String getBookFlightCount (int recordType);
  void editFlightRecord (int recordID, String fieldName, String newValue);
  int bookFlight (String firstName, String lastName, String address, String phone, String destination, String date, int seatClass);
  boolean transferReservation (int passangerID, int currentCity, int otherCity);
} // interface IFlightServerOperations
