package flightreservation;


/**
* flightreservation/FlightReservationSystem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/alvaro/Documents/Workspaces/eclipse/CorbaFlightReservation/src/FlightReservation.idl
* Wednesday, October 26, 2016 8:08:12 PM EDT
*/

public interface FlightReservationSystem extends FlightReservationSystemOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FlightReservationSystem
