package flightreservation;

/**
* flightreservation/FlightReservationSystemHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/alvaro/Documents/Workspaces/eclipse/CorbaFlightReservation/src/FlightReservation.idl
* Wednesday, October 26, 2016 8:08:12 PM EDT
*/

public final class FlightReservationSystemHolder implements org.omg.CORBA.portable.Streamable
{
  public flightreservation.FlightReservationSystem value = null;

  public FlightReservationSystemHolder ()
  {
  }

  public FlightReservationSystemHolder (flightreservation.FlightReservationSystem initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = flightreservation.FlightReservationSystemHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    flightreservation.FlightReservationSystemHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return flightreservation.FlightReservationSystemHelper.type ();
  }

}
