package flightreservation;


/**
* flightreservation/FlightReservationSystemOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/alvaro/Documents/Workspaces/eclipse/CorbaFlightReservation/src/FlightReservation.idl
* Wednesday, October 26, 2016 8:08:12 PM EDT
*/

public interface FlightReservationSystemOperations 
{
  String editFlightRecord (String adminUser, String flightInfo, short operationType);
  String getBookedFlightCount (short type);
  String transferReservation (short passengerId, String currentCity, String destinationCity);
  String bookFlight (String firstName, String lastName, String address, String phone, String destination, int date, short type);
} // interface FlightReservationSystemOperations
